title: My personal blog - Görkem Tosun
email: gorkemtosun@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This Blog presents my various studies. I am an engineer, interested in programming, electronics, DIY and all kind of technology. 
  #Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Görkem Tosun # add your name
author-pic: ProfilePic.jpg
about-author: This Blog will present my various studies about almost everything that I am involved to.

# Contact links
phone: +905554493747
website: https://gorkemtosun.com
linkedin: gorkemtosun
github: grkmus # Add your Github handle
twitter: '@tosungo' # Add your Twitter handle
facebook: GrkmTsn # Add your Facebook handle
instagram: tosungo
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
